import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "New KNN Web-tech project template",
  description: "Generated by KNN Web-tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
